CREATE TABLE EMPLOYEE
(
EMP_ID INT,
EMP_NAME VARCHAR(20),
CITY VARCHAR(20)
);

CREATE TABLE COMPANY
(
EMP_ID INT,
COMPANY_NAME VARCHAR(20),
SALARY INT
);

INSERT INTO EMPLOYEE VALUES
(1,'RAM','PUNE');

INSERT INTO EMPLOYEE VALUES
(2,'SHAM','MUMBAI');

INSERT INTO EMPLOYEE VALUES
(3,'RAHUL','NASHIK');

INSERT INTO COMPANY VALUES
(1,'TCS',50000);

INSERT INTO COMPANY VALUES
(2,'INFOSYS',60000);

INSERT INTO COMPANY VALUES
(3,'WIPRO',45000);

SELECT EMPLOYEE.EMP_NAME,
EMPLOYEE.CITY,
COMPANY.COMPANY_NAME,
COMPANY.SALARY
FROM EMPLOYEE
INNER JOIN COMPANY
ON EMPLOYEE.EMP_ID=COMPANY.EMP_ID;

CREATE VIEW EMP_DETAILS AS
SELECT EMP_NAME,CITY
FROM EMPLOYEE;

SELECT * FROM EMP_DETAILS;

SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_ID IN
(
SELECT EMP_ID
FROM COMPANY
WHERE SALARY>50000
);